theme: jekyll-theme-minimal
title: Chandan Narayan
description: Dept. of Languages, Literatures, and Linguistics 
description: Speech and Psycholinguistics Lab
description: Specialized Program in Speech and Language Science
